image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

build: off  # будем использовать свой скрипт сборки

build_script:
  - ./gradlew test --info -Dselenide.headless=true # запускаем тест, флаг --info позволяет выводить больше информации
